use_dataset_env: true

agent:
  type: mimocode-agent
  tools:
    - tool: bash
      config:
        timeout: 60
        max_timeout: 300
    - tool: read
    - tool: write
    - tool: edit
    - tool: grep
    - tool: glob
    - tool: task
  step_limit: 500

environment:
  cwd: "/testbed"
  timeout: 300
  environment_class: kubernetes
  node_selector: {}
  cpu_request: "0.5"
  memory_request: "1Gi"
  cpu_limit: "4"
  memory_limit: "8Gi"
  labels: {}
  host_network: false
  anti_hack_cleanup: true
  raise_on_transport_error: true

model:
  model_name: policy
  protocol: chat
  model_kwargs:
    temperature: 1.0
