- name: mimo_swe_agent
  _target_: recipes.arvo.agent_loop.ArvoAgentLoop
  mimoagent_config_path: config/agent/arvo/arvo.yaml

  per_turn_max_tokens: 32768
  reward_timeout: 0
  env_setup_timeout: ${oc.env:ENV_SETUP_TIMEOUT,900}
  fail_on_env_setup_error: ${oc.env:FAIL_ON_ENV_SETUP_ERROR,false}
  invalid_reward_for_infra: ${oc.env:INVALID_REWARD_FOR_INFRA,false}
  trajectory_timeout: ${oc.env:TRAJECTORY_TIMEOUT,28800}
  env_num_cpus: ${oc.env:ENV_NUM_CPUS,0.125}
  env_scheduling_strategy: SPREAD
  agent_thread_pool_size: 128
